name: Build MT7621 JDC-1

on: 
  repository_dispatch:
  workflow_dispatch:
  #  release:
    #  types: [published]
#  push:
#    tags:
#    - 'v*'
  #  branches: 
  #    - master
#  schedule:
 #   - cron: 0 17 * * 4
#  watch:
   # types: [started]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo 'Run lscpu:'
        lscpu
        echo 'Run df -h:'
        df -h
        echo 'Run free -h:'
        free -h
        
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        echo 'current dir:'
        pwd
        mkdir -p /mnt/rt-n56u
        git clone --depth=1 https://github.com/CopyPasteByteArtist/chongshengB-rt-n56u.git /mnt/rt-n56u
        sed -i 's/192.168.2/192.168.68/g' /mnt/rt-n56u/trunk/user/shared/defaults.h
        sed -i 's/ntp1.aliyun.com/time.pool.aliyun.com/g' /mnt/rt-n56u/trunk/user/shared/defaults.h
        sed -i 's/2001:470:0:50::2/time.asia.apple.com/g' /mnt/rt-n56u/trunk/user/shared/defaults.h
        echo 'cat /mnt/rt-n56u/trunk/user/shared/defaults.h:'
        cat /mnt/rt-n56u/trunk/user/shared/defaults.h
        
        echo 'cat /mnt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat'
        cat /mnt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat
        
        rm -f /mnt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat
        
        cp -vpf l1profile.dat /mnt/rt-n56u/trunk/configs/boards/JDC-1
        
        echo 'cat /mnt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat'
        cat /mnt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat
        
        cd /mnt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh

        echo 'Run ls -la /mnt/rt-n56u/toolchain-mipsel:'
        ls -la /mnt/rt-n56u/toolchain-mipsel
        mkdir -p /mnt/images/
    - name: Build Firmware
      env:
        TNAME: "JDC-1"
      run: |
        echo "FILE_DATE=-$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        cp -vpf $TNAME.config /mnt/rt-n56u/trunk/.config
        cat /mnt/rt-n56u/trunk/.config
        cd /mnt/rt-n56u/trunk
        sudo ./clear_tree_simple
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /mnt/images
        sudo cp -vpf .config /mnt/images
        # done
    - name : Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: Padavan-MT7621-JDC-1-C${{ env.FILE_DATE }}
        path: /mnt/images
