name: Build MT7621 JDC-1

on: 
  repository_dispatch:
  workflow_dispatch:

env:
  TNAME: "JDC-1"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo 'Run lscpu:'
        lscpu
        echo 'Run df -h:'
        df -h
        echo 'Run free -h:'
        free -h
        
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        echo 'current dir:'
        pwd
        mkdir -p /opt/rt-n56u
        git clone --depth=1 https://github.com/CopyPasteByteArtist/chongshengB-rt-n56u.git /opt/rt-n56u
        sed -i 's/192.168.2/192.168.68/g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sed -i 's/ntp1.aliyun.com/time.pool.aliyun.com/g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sed -i 's/2001:470:0:50::2/time.asia.apple.com/g' /opt/rt-n56u/trunk/user/shared/defaults.h
        echo 'cat /opt/rt-n56u/trunk/user/shared/defaults.h:'
        cat /opt/rt-n56u/trunk/user/shared/defaults.h
        
        echo 'cat /opt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat'
        cat /opt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat
        
        rm -f /opt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat
        cp -vpf $GITHUB_WORKSPACE/$TNAME/l1profile.dat /opt/rt-n56u/trunk/configs/boards/JDC-1
        
        echo 'cat /opt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat'
        cat /opt/rt-n56u/trunk/configs/boards/JDC-1/l1profile.dat
        
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh

        echo 'Run ls -la /opt/rt-n56u/toolchain-mipsel:'
        ls -la /opt/rt-n56u/toolchain-mipsel
        mkdir -p /opt/images/
    - name: Build Firmware
      run: |
        echo "FILE_DATE=-$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        cp -vpf $GITHUB_WORKSPACE/$TNAME/$TNAME.config /opt/rt-n56u/trunk/.config
        cat /opt/rt-n56u/trunk/.config
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree_simple
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images
        sudo cp -vpf .config /opt/images
    - name : Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: Padavan-MT7621-JDC-1-C${{ env.FILE_DATE }}
        path: /opt/images
